import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/Navbar'
import Header from '../containers/Header'
import WhatGpt from '../containers/WhatGpt'
import Contact_us from '../containers/Contact_us'
import Vr_ai from '../containers/Vr_ai'
import Blogs from '../containers/Blogs'
import Footer from '../containers/Footer'
export default function Home() {
  return (
    <>
    
      <Head>
        <title>OpenAI-ChatGPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.svg" />

        
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Header />
        <WhatGpt />
        <Contact_us id='contact_us' />
        <Vr_ai />
        <Blogs />
        <Footer/>
      </main>
    </>
  )
}
